# Generated by Django 4.2.30 on 2026-09-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken_notification_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='translation_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='translation_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
