# Generated by Django 5.2.14 on 2026-06-19 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_city_user_governorate_user_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. Home, Office', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('governorate', models.CharField(blank=True, choices=[('cairo', 'Cairo'), ('giza', 'Giza'), ('alexandria', 'Alexandria'), ('beni_suef', 'Beni Suef'), ('qalyubia', 'Qalyubia'), ('sharqia', 'Sharqia'), ('dakahlia', 'Dakahlia'), ('minya', 'Minya'), ('fayoum', 'Fayoum'), ('asyut', 'Asyut'), ('sohag', 'Sohag'), ('luxor', 'Luxor'), ('aswan', 'Aswan'), ('port_said', 'Port Said'), ('suez', 'Suez'), ('ismailia', 'Ismailia'), ('damietta', 'Damietta'), ('kafr_sheikh', 'Kafr El-Sheikh'), ('gharbia', 'Gharbia'), ('menofia', 'Menofia'), ('beheira', 'Beheira'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('new_valley', 'New Valley'), ('matrouh', 'Matrouh'), ('north_sinai', 'North Sinai'), ('south_sinai', 'South Sinai')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default', 'id'],
            },
        ),
    ]
