# Generated by Django 4.2.30 on 2026-07-13 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_google_auth_and_cleanup'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_google__98b509_idx',
            old_name='users_google_id_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_profile_fa23f2_idx',
            old_name='users_profile_completed_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, optional +, spaces, dashes).', regex='^\\+?[0-9 ()-]{7,20}$')]),
        ),
    ]
