# Generated by Django 4.2.30 on 2026-07-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_worker_verification_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_verific_b8b125_idx',
            old_name='users_verificati_status_idx',
        ),
    ]
