# Generated by Django 4.2.30 on 2026-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_users_verificati_status_idx_users_user_verific_b8b125_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', help_text='Preferred language for notifications.', max_length=5),
        ),
    ]
