# Generated by Django 4.2.30 on 2026-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_language_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture_url',
            field=models.URLField(blank=True, default='', help_text='Google profile picture URL (not stored locally).', max_length=500),
        ),
    ]
