# Generated by Django 4.2.30 on 2026-09-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_address_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('WORKER_DELAY', 'Worker delay'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
