# Generated by Django 4.2.30 on 2026-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotline_phone', models.CharField(blank=True, default='', help_text='Emergency hotline shown on the landing page.', max_length=30)),
                ('support_phone', models.CharField(blank=True, default='', help_text='Support phone shown in the footer.', max_length=30)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('working_hours', models.CharField(blank=True, default='', max_length=120)),
                ('response_time_text', models.CharField(blank=True, default='', help_text="Landing page 'average response time' wording (admin-editable text).", max_length=120)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('app_store_url', models.URLField(blank=True, default='', help_text='iOS / App Store download link.')),
                ('play_store_url', models.URLField(blank=True, default='', help_text='Android / Google Play download link.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
