// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOsnl6g-pWrurQTLK73m_z1SEhkkf5ieY',
    appId: '1:945925867568:web:a60adf00ee4815580345f5',
    messagingSenderId: '945925867568',
    projectId: 'mongez-86fdf',
    authDomain: 'mongez-86fdf.firebaseapp.com',
    storageBucket: 'mongez-86fdf.firebasestorage.app',
    measurementId: 'G-W83WRY6W00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1kgBlng3o0g2R85LBNgfKTMB0zbl0obY',
    appId: '1:945925867568:android:c481f2be939112430345f5',
    messagingSenderId: '945925867568',
    projectId: 'mongez-86fdf',
    storageBucket: 'mongez-86fdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ilxVyh8blFUuKLhoEW0J6Rwz8Q72PYc',
    appId: '1:945925867568:ios:f1dd0fbf34b9869f0345f5',
    messagingSenderId: '945925867568',
    projectId: 'mongez-86fdf',
    storageBucket: 'mongez-86fdf.firebasestorage.app',
    iosBundleId: 'com.example.mongez',
  );
}
